# mysql 数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://110.40.241.31:3306/project?serverTimezone=GMT%2B8&charactorEncoding=utf-8
    username: root
    password: Cyb666666@
  profiles:
    active: dev
#mybatis 日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:xml/**/*.xml
  global-config:
    db-config:
      id-type: auto #设置主键生成算法为 自增
server:
  port: 8000
